<?php

namespace AppBundle\Repository;

/**
 * CursoUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
