<?php

namespace AppBundle\Repository;

/**
 * EncuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuestaRepository extends \Doctrine\ORM\EntityRepository
{

	public function mostarEncuestasCursoActivo()	{

		try {
			$query = "SELECT enc.id, enc.titulacion_id as titulacion_id, enc.usuario_id as usuario, enc.evaluado_id as evaluado, c.descripcion as curso, tit.nombre as titulacion, usu.username, usu.nombre as nombre_usuario, usu.apellidos, enc.naevaluado
						from encuesta enc
                        			INNER JOIN usuario usu on usu.id = enc.usuario_id
						INNER JOIN titulacion tit on enc.titulacion_id = tit.id
						INNER JOIN curso_titulacion ct on ct.titulacion_id = tit.id
						INNER JOIN curso c on c.id = ct.curso_id
                        			WHERE c.activo = 1";
			$em  = $this->getEntityManager();
			$db = $em->getConnection();
			$stmt = $db->prepare($query);
			$param = array();
			$stmt->execute($param);
			$res = $stmt->fetchAll();
	    } catch (\Doctrine\ORM\NoResultException $exception) {
	        return null;
	    }
		return $res;
	}
}
