<?php

namespace AppBundle\Repository;

/**
 * TitulacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitulacionRepository extends \Doctrine\ORM\EntityRepository
{
	public function mostarTitulacionesCursoActivo()	{

		try {
			$query = "SELECT tit.*
						from titulacion tit
						INNER JOIN curso_titulacion ct on ct.titulacion_id = tit.id
						INNER JOIN curso cu on ct.curso_id = cu.id
						WHERE cu.activo = 1
						ORDER BY tit.nombre";
			$em  = $this->getEntityManager();
			$db = $em->getConnection();
			$stmt = $db->prepare($query);
			$param = array();
			$stmt->execute($param);
			$res = $stmt->fetchAll();

	    } catch (\Doctrine\ORM\NoResultException $exception) {
	        return null;
	    }
	    return $res;
	}

	public function titulacionesCursoActivo()	{

		try {
			$query = "SELECT t.id, t.nombre, t.codigo FROM titulacion t
						INNER JOIN curso_titulacion ct on ct.titulacion_id = t.id
						INNER JOIN curso c ON c.id = ct.curso_id AND c.activo = 1
						ORDER BY t.nombre";

			$em  = $this->getEntityManager();
			$db = $em->getConnection();
			$stmt = $db->prepare($query);
			$param = array();
			$stmt->execute($param);
			$res = $stmt->fetchAll();

	    } catch (\Doctrine\ORM\NoResultException $exception) {
	        return null;
	    }
		return $res;
	}



}
