#app:
 #   resource: '@AppBundle/Controller/'
  #  type: annotation


#app:
#  resource: '@AppBundle/Resources/config/routing.yml'
#  prefix: /

########    LOGIN/LOGOUT  ##########
login:
    path: /
    defaults: { _controller: AppBundle:Security:loginAdmin }

login_check:
    path: /login_check

logout:
    path: /logout


inicio:
    path: /inicio
    defaults: { _controller: AppBundle:Inicio:inicio }

mostrar_usuarios:
    path: /admin/{_locale}/usuarios
    defaults: { _controller: AppBundle:Usuario:mostrarUsuarios,_locale: es }
    requirements:
        _locale: 'en|es'

mostrar_usuario:
    path:  /admin/{_locale}/mostrar/usuario/{idUsuario}
    defaults: { _controller: AppBundle:Usuario:mostrarUsuario, _locale: es }
    requirements:
        _locale: 'en|es'
        idUsuario: \d+

crear_usuario:
    path:  /admin/{_locale}/crear/usuario
    defaults: { _controller: AppBundle:Usuario:crearUsuario, _locale: es }
    requirements:
        _locale: 'en|es'

editar_usuario:
    path:   /admin/{_locale}/editar/usuario/{idUsuario}
    defaults: {_controller: AppBundle:Usuario:editarUsuario, _locale: es}
    requirements:
        _locale: 'en|es'
#        idUsuario: \d+

eliminar_usuario:
    path:   /admin/{_locale}/eliminar/usuario/{idUsuario}
    defaults: {_controller: AppBundle:Usuario:eliminarUsuario, _locale: es}
    requirements:
        _locale: 'en|es'
        idUsuario: \d+

buscar_usuario_letra:
    path:  /admin/{_locale}/usuarios/{letra}
    defaults: { _controller: AppBundle:Usuario:buscaUsarioLetra, _locale: es }
    requirements:
        _letra: 'a|b|c|d|e|f|g|h|i|j|k|l|m|n|ñ|o|p|q|r|s|t|u|v|w|x|y|z'

buscar_general:
    path:  /admin/{_locale}/busqueda
    defaults: { _controller: AppBundle:Usuario:busquedaGeneral, _locale: es }
    requirements:
        _locale: 'en|es'

prueba:
    path:  /admin/{_locale}/prueba
    defaults: { _controller: AppBundle:Usuario:prueba, _locale: es }
    requirements:
        _locale: 'en|es'

crear_titulacion:
    path:  /admin/{_locale}/crear/titulacion
    defaults: { _controller: AppBundle:Titulacion:crearTitulacion, _locale: es }
    requirements:
        _locale: 'en|es'

mostrar_titulaciones:
    path:  /admin/{_locale}/mostrar/titulaciones
    defaults: { _controller: AppBundle:Titulacion:mostrarTitulaciones, _locale: es }
    requirements:
        _locale: 'en|es'

eliminar_titulacion:
    path:  /admin/{_locale}/eliminar/titulacion/{idTitulacion}
    defaults: { _controller: AppBundle:Titulacion:eliminarTitulacion, _locale: es }
    requirements:
        _locale: 'en|es'
        idTitulacion: \d+

editar_titulacion:
    path:  /admin/{_locale}/editar/titulacion/{idTitulacion}
    defaults: { _controller: AppBundle:Titulacion:editarTitulacion, _locale: es }
    requirements:
        _locale: 'en|es'
        idTitulacion: \d+

mostrar_preguntas:
    path:  /admin/{_locale}/mostrar/preguntas
    defaults: { _controller: AppBundle:Pregunta:mostrarPreguntas, _locale: es }
    requirements:
        _locale: 'en|es'

crear_pregunta:
    path:  /admin/{_locale}/crear/pregunta/
    defaults: { _controller: AppBundle:Pregunta:crearPregunta, _locale: es }
    requirements:
        _locale: 'en|es'

editar_pregunta:
    path:  /admin/{_locale}/editar/pregunta/{idPregunta}
    defaults: { _controller: AppBundle:Pregunta:editarPregunta, _locale: es }
    requirements:
        _locale: 'en|es'
        idPregunta: \d+

eliminar_pregunta:
    path:  /admin/{_locale}/eliminar/pregunta/{idPregunta}
    defaults: { _controller: AppBundle:Pregunta:eliminarPregunta, _locale: es }
    requirements:
        _locale: 'en|es'
        idPregunta: \d+

crear_curso:
    path:  /admin/{_locale}/crear/curso/
    defaults: { _controller: AppBundle:Curso:crearCurso, _locale: es }
    requirements:
        _locale: 'en|es'

editar_curso:
    path:  /admin/{_locale}/crear/curso/{idCurso}
    defaults: { _controller: AppBundle:Curso:editarCurso, _locale: es }
    requirements:
        _locale: 'en|es'
        idCurso: \d+

eliminar_curso:
    path:  /admin/{_locale}/eliminar/curso/{idCurso}
    defaults: { _controller: AppBundle:Curso:eliminarCurso, _locale: es }
    requirements:
        _locale: 'en|es'
        idCurso: \d+

mostrar_cursos:
    path:  /admin/{_locale}/mostrar/cursos
    defaults: { _controller: AppBundle:Curso:mostrarCursos, _locale: es }
    requirements:
        _locale: 'en|es'

crear_encuesta:
    path:  /admin/{_locale}/crear/encuesta/
    defaults: { _controller: AppBundle:Encuesta:crearEncuesta, _locale: es }
    requirements:
        _locale: 'en|es'

eliminar_encuesta:
    path:  /admin/{_locale}/eliminar/encuesta/{idEncuesta}
    defaults: { _controller: AppBundle:Encuesta:eliminarEncuesta, _locale: es }
    requirements:
        _locale: 'en|es'
        idEncuesta: \d+

#editar_encuesta:
#    path:  /admin/{_locale}/crear/encuesta/{idEncuesta}
#    defaults: { _controller: AppBundle:Encuesta:editarEncuesta, _locale: es }
#    requirements:
#        _locale: 'en|es'
#        idEncuesta: \d+