#app:
 #   resource: '@AppBundle/Controller/'
  #  type: annotation


#app:
#  resource: '@AppBundle/Resources/config/routing.yml'
#  prefix: /

########    LOGIN/LOGOUT  ##########
login:
    path: /
    defaults: { _controller: AppBundle:Security:loginAdmin }

login_check:
    path: /login_check

logout:
    path: /logout


inicio:
    path: /inicio
    defaults: { _controller: AppBundle:Inicio:inicio }

mostrar_usuarios:
    path: /admin/usuarios
    defaults: { _controller: AppBundle:Usuario:mostrarUsuarios }

buscar_usuario_letra:
    path:  /admin/usuarios/{letra}
    defaults: { _controller: AppBundle:Usuario:buscaUsarioLetra }
    requirements:
        _letra: 'a|b|c|d|e|f|g|h|i|j|k|l|m|n|ñ|o|p|q|r|s|t|u|v|w|x|y|z'

buscar_general:
    path:  /admin/busqueda
    defaults: { _controller: AppBundle:Usuario:busquedaGeneral }

