app:
    resource: '@AppBundle/Controller/'
    type: annotation


#app:
#  resource: '@AppBundle/Resources/config/routing.yml'
#  prefix: /

inicio:
    path: /inicio
    defaults: { _controller: AppBundle:Inicio:inicio }